// src/App.vue
<template>
  <div class="overflow-x-hidden" :class="{ 'mode-dark': darkModeEnabled }">
    <intro-screen />
    <div
      class="relative bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-400 font-semibold"
      :class="{ 'easter-egg': easterEggEnabled }"
    >
      <div
        class="bottom-0 pb-8 absolute z-40 flex justify-end w-screen pointer-events-none"
        style="min-width: 3200px"
      >
        <div class="text-6xl mr-4 font-bold" style="writing-mode: vertical-rl">
          Woah, you have an insanely wide monitor
        </div>
      </div>
      <div
        class="absolute z-0 dots right-0 top-0 w-16 md:w-32 mt-12"
        style="height: 24rem"
      />
      <div
        class="absolute z-0 dots left-0 bottom-0 h-8 md:h-32 ml-12"
        style="width: 18rem"
      />
      <theme-button
        @click="darkModeEnabled = !darkModeEnabled"
        :dark-mode-enabled="darkModeEnabled"
      />
      <div class="relative z-10 max-w-4xl mx-auto px-8">
        <jumbotron />
        <main-content v-bind="{ projects, skills }" />
        <site-footer />
      </div>
    </div>
  </div>
</template>

<script>
import Konami from "konami";

import IntroScreen from "./IntroScreen.vue";
import Jumbotron from "./Jumbotron.vue";
import MainContent from "./MainContent.vue";
import SiteFooter from "./SiteFooter.vue";
import ThemeButton from "./ThemeButton.vue";

export default {
  name: "App",
  components: { IntroScreen, Jumbotron, MainContent, SiteFooter, ThemeButton },
  props: ["projects", "skills"],
  data() {
    return {
      easterEggEnabled: false,
      darkModeEnabled:
        window.matchMedia &&
        window.matchMedia("(prefers-color-scheme: dark)").matches
    };
  },
  mounted() {
    let vm = this;

    new Konami(() => {
      vm.easterEggEnabled = !vm.easterEggEnabled;
    });
  }
};
</script>

<style scoped>
.dots {
  background-image: url(/images/300.png);
}

.mode-dark .dots {
  background-image: url(/images/800.png);
}

.easter-egg {
  background-image: url("/images/nezuko.gif");
}

.easter-egg >>> * {
  animation: rainbow 5s linear;
  animation-iteration-count: infinite;
}

@keyframes rainbow {
  100%,
  0% {
    color: rgb(255, 0, 0);
  }
  8% {
    color: rgb(255, 127, 0);
  }
  16% {
    color: rgb(255, 255, 0);
  }
  25% {
    color: rgb(127, 255, 0);
  }
  33% {
    color: rgb(0, 255, 0);
  }
  41% {
    color: rgb(0, 255, 127);
  }
  50% {
    color: rgb(0, 255, 255);
  }
  58% {
    color: rgb(0, 127, 255);
  }
  66% {
    color: rgb(0, 0, 255);
  }
  75% {
    color: rgb(127, 0, 255);
  }
  83% {
    color: rgb(255, 0, 255);
  }
  91% {
    color: rgb(255, 0, 127);
  }
}
</style>

// src/App.svelte
<script>
  import { onMount } from 'svelte';
  import Konami from "konami";

  import Shapes from "./Shapes.svelte";
  import Jumbotron from "./Jumbotron.svelte";
  import Project from "./Project.svelte";
  import Sun from "./icons/Sun.svelte";
  import Moon from "./icons/Moon.svelte";
  import projects from './projects.yaml';

  let modeDark =
    window.matchMedia
    && window.matchMedia("(prefers-color-scheme: dark)").matches;
  let easterEgg = false;

  onMount(() => {
    new Konami(() => {
      easterEgg = !easterEgg;
    });
  });
</script>

<app
  class="block"
  class:mode-dark="{modeDark}"
  class:easter-egg="{easterEgg}"
>
  <div class="fixed z-50 top-0 right-0 p-4 sm:p-6">
    <button
      class="bg-gray-800 dark:bg-gray-300 hover:bg-gray-900 dark-hover:bg-gray-100 rounded-full p-1 shadow-xl outline-none focus:shadow-outline"
      on:click="{() => modeDark = !modeDark}"
    >
      {#if modeDark}
        <Sun class="w-6 h-6 text-gray-800" />
      {:else}
        <Moon class="w-6 h-6 text-blue-100" />
      {/if}
    </button>
  </div>
  <div class="relative z-10 overflow-x-hidden bg-gray-200 text-gray-900 dark:bg-gray-900 dark:text-gray-300 nezuko">
    <div class="relative pt-32 pb-48 sm:py-0 sm:min-h-screen flex justify-center items-center">
      <Shapes isDark="{modeDark}" easterEgg="{easterEgg}" />
      <Jumbotron />
    </div>
    <div class="relative -mt-10 z-10 mb-24 max-w-3xl mx-auto px-6">
      <h2 class="dark:text-gray-300 font-bold text-5xl">Projects</h2>
      <hr class="border-blue-500 dark:border-blue-600 border-4 inline-block w-32 ml-2 mb-4" />
      <div class="grid row-gap-12">
        {#each projects as project}
          <Project {...project} />
        {/each}
      </div>
    </div>
    <dots
      class="absolute z-0 bottom-0 ml-2 w-8 md:w-32 opacity-50"
      style="height: 20rem"
    />
  </div>
</app>
